---
micronaut:
  application:
    name: kafka37

---
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

---
kafka:
  bootstrap:
    servers: localhost:9092

---
endpoints:
  metrics:
    enabled: true
    sensitive: false
  prometheus:
    enabled: true
    sensitive: false
